### ISSUE TITLE
Do not turn on all modules

### ISSUE THREAD

**Issue by fdkong** [WilkAndy/ba_hun#46]
BaHun needs `RICHARDS` only.

**Comment by WilkAndy** [comment]
I'm pretty sure BaHun is being used for simulations involving coupling to tensor_mechanics too.

**Comment by fdkong** [comment]
I did not detect any errors without tensor_mechanics

**Comment by WilkAndy** [comment]
So for the test suite that appears to be true.  But i'm thinking of users who are running their simulations using BaHun.  They might be using tensor_mechanics.

**Comment by fdkong** [comment]
Could you give me a list what you need?

**Comment by WilkAndy** [comment]
Yea, i think  richards, tensor_mechanics, fluid_properties should be enough
